[package]
name = "hypervariate_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
serde = { version = "1.0.162", features = ["derive"] }

[dev-dependencies]
rand = "0.8.5"
